name: Setup Terraform S3 Backend

on:
  workflow_dispatch:

jobs:
  setup-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Check if S3 bucket exists
        id: check_bucket
        run: |
          if aws s3api head-bucket --bucket meu-bucket-terraform-state 2>/dev/null; then
            echo "Bucket exists"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Bucket does not exist"
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create S3 bucket if not exists
        if: steps.check_bucket.outputs.exists == 'false'
        run: |
          aws s3api create-bucket --bucket meu-bucket-terraform-state --region us-east-1 --create-bucket-configuration LocationConstraint=us-east-1
          aws s3api put-bucket-versioning --bucket meu-bucket-terraform-state --versioning-configuration Status=Enabled


